openapi: 3.0.0
info:
  title: OCR api
  description: API for managing OCR apps
  version: 1.0.0

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost

paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

  /api/image/update:
    post: 
      summary: update image
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Image"
        "500":
          description: Internal Server Error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        # Other user properties

    Image:
      type: object
      properties:
        telecon_entry_id:
          type: string
        image_name:
          type: string
        loacation:
          type: string
        lesions_appear:
          type: boolean
          default: false
        annotation:
          type: array
          default: []
        predicted_vat:
          type: string
        # Other image properties
