openapi: 3.0.0
info:
  title: OCR api
  description: API for managing OCR apps
  version: 1.0.0

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost


paths:
  /api/dashboard/percentages:
    get:
      summary: Get the percentage of risk habits
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RiskHabitPercentage"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/dashboard/totals:
    get:
      summary: Get the total number of doctors, images and patients
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  doctors:
                    type: integer
                    description: Number of doctors
                    example: 10
                  images:
                    type: integer
                    description: Number of images
                    example: 100
                  patients:
                    type: integer
                    description: Number of patients
                    example: 1000
                    $ref: "#/components/schemas/TotalCounts"
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"




components:
  schemas:
    RiskHabitPercentage:
      type: object
      properties:
        item:
          type: string
          description: Name of the risk habit
          example: Smoking
        percentage:
          type: number
          description: >
            Percentage of patients with this habit.
            Example: If there are 100 patients and 20 of them have the 'Smoking' habit, the percentage is 20%.
          example: 20

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: Unauthorized access

    TotalCounts:
      type: object
      properties:
        doctors:
          type: integer
          description: Total number of doctors
          example: 10
        patients:
          type: integer
          description: Total number of patients
          example: 50
        images:
          type: integer
          description: Total number of images
          example: 100

 



