openapi: 3.0.0
info:
  title: OCR api 
  description: API for managing OCR apps
  version: 1.0.0

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://localhost

paths:
  /api/admin/auth/signup:
    post:
      summary: To add the initial admin
      requestBody:
        required: true
        content:
          application/json:
            schema:  
              $ref: "#/components/schemas/NewAdminSignUp"
      responses: 
        "200":
          description: "Successfully signed in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewAdminSignUpResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    

components:
  schemas:
    NewAdminSignUp:
      type: object
      properties:
        reg_no:
          type: string
        username:
          type: string
        email:
          type: string
        hospital:
          type: string
        role:
          type: string
          
    NewAdminSignUpResponse:
      type: object
      properties:
        reg_no:
          type: string
        username:
          type: string
        email:
          type: string
        hospital:
          type: string
        role:
          type: string
    
